# Site settings
title: A Technical Travesty
description: > # this means to ignore newlines until "baseurl:"
  Random technical writings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jacobsimpson.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
