baseURL = "http://jacobsimpson.github.io/"
languageCode = "en-us"
title = "Technotes"
theme = "minimo"
publishdir = ".."

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
#sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]

[params.search]
client = "lunr"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params.assets]
favicon = "favicon.ico"

[about]
title = ""
description = ""
logo = "/images/logo.png"
